<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Kota;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('kotas')->delete();

        $data = [
            ['id' => 1101, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Simeulue'],
            ['id' => 1102, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Singkil'],
            ['id' => 1103, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Selatan'],
            ['id' => 1104, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Tenggara'],
            ['id' => 1105, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Timur'],
            ['id' => 1106, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Tengah'],
            ['id' => 1107, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Barat'],
            ['id' => 1108, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Besar'],
            ['id' => 1109, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Pidie'],
            ['id' => 1110, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Bireuen'],
            ['id' => 1111, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Utara'],
            ['id' => 1112, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Barat Daya'],
            ['id' => 1113, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Gayo Lues'],
            ['id' => 1114, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Tamiang'],
            ['id' => 1115, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Nagan Raya'],
            ['id' => 1116, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Aceh Jaya'],
            ['id' => 1117, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Bener Meriah'],
            ['id' => 1118, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kabupaten Pidie Jaya'],
            ['id' => 1171, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kota Banda Aceh'],
            ['id' => 1172, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kota Sabang'],
            ['id' => 1173, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kota Langsa'],
            ['id' => 1174, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kota Lhokseumawe'],
            ['id' => 1175, 'provinsi_id' => 1, 'nm_kab_kota' => 'Kota Subulussalam'],
            ['id' => 1201, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Nias'],
            ['id' => 1202, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Mandailing Natal'],
            ['id' => 1203, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Tapanuli Selatan'],
            ['id' => 1204, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Tapanuli Tengah'],
            ['id' => 1205, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Tapanuli Utara'],
            ['id' => 1206, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Toba Samosir'],
            ['id' => 1207, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Labuhan Batu'],
            ['id' => 1208, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Asahan'],
            ['id' => 1209, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Simalungun'],
            ['id' => 1210, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Dairi'],
            ['id' => 1211, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Karo'],
            ['id' => 1212, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Deli Serdang'],
            ['id' => 1213, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Langkat'],
            ['id' => 1214, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Nias Selatan'],
            ['id' => 1215, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Humbang Hasundutan'],
            ['id' => 1216, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Pakpak Bharat'],
            ['id' => 1217, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Samosir'],
            ['id' => 1218, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Serdang Bedagai'],
            ['id' => 1219, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Batu Bara'],
            ['id' => 1220, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Padang Lawas Utara'],
            ['id' => 1221, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Padang Lawas'],
            ['id' => 1222, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Labuhan Batu Selatan'],
            ['id' => 1223, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Labuhan Batu Utara'],
            ['id' => 1224, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Nias Utara'],
            ['id' => 1225, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kabupaten Nias Barat'],
            ['id' => 1271, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Sibolga'],
            ['id' => 1272, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Tanjung Balai'],


            ['id' => 1273, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Pematang Siantar'],
            ['id' => 1274, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Tebing Tinggi'],
            ['id' => 1275, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Medan'],
            ['id' => 1276, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Binjai'],
            ['id' => 1277, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Padangsidimpuan'],
            ['id' => 1278, 'provinsi_id' => 2, 'nm_kab_kota' => 'Kota Gunungsitoli'],
            ['id' => 1301, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Kepulauan Mentawai'],
            ['id' => 1302, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Pesisir Selatan'],
            ['id' => 1303, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Solok'],
            ['id' => 1304, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Sijunjung'],
            ['id' => 1305, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Tanah Datar'],
            ['id' => 1306, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Padang Pariaman'],
            ['id' => 1307, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Agam'],
            ['id' => 1308, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Lima Puluh Kota'],
            ['id' => 1309, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Pasaman'],
            ['id' => 1310, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Solok Selatan'],
            ['id' => 1311, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Dharmasraya'],
            ['id' => 1312, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kabupaten Pasaman Barat'],
            ['id' => 1371, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kota Padang'],
            ['id' => 1372, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kota Solok'],
            ['id' => 1373, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kota Sawah Lunto'],
            ['id' => 1374, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kota Padang Panjang'],
            ['id' => 1375, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kota Bukittinggi'],
            ['id' => 1376, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kota Payakumbuh'],
            ['id' => 1377, 'provinsi_id' => 3, 'nm_kab_kota' => 'Kota Pariaman'],
            ['id' => 1401, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Kuantan Singingi'],
            ['id' => 1402, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Indragiri Hulu'],
            ['id' => 1403, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Indragiri Hilir'],
            ['id' => 1404, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Pelalawan'],
            ['id' => 1405, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Siak'],
            ['id' => 1406, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Kampar'],
            ['id' => 1407, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Rokan Hulu'],
            ['id' => 1408, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Bengkalis'],
            ['id' => 1409, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Rokan Hilir'],
            ['id' => 1410, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kabupaten Kepulauan Meranti'],
            ['id' => 1471, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kota Pekanbaru'],
            ['id' => 1473, 'provinsi_id' => 4, 'nm_kab_kota' => 'Kota Dumai'],
            ['id' => 1501, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Kerinci'],
            ['id' => 1502, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Merangin'],
            ['id' => 1503, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Sarolangun'],
            ['id' => 1504, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Batang Hari'],
            ['id' => 1505, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Muaro Jambi'],
            ['id' => 1506, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Tanjung Jabung Timur'],
            ['id' => 1507, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Tanjung Jabung Barat'],
            ['id' => 1508, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Tebo'],
            ['id' => 1509, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kabupaten Bungo'],
            ['id' => 1571, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kota Jambi'],
            ['id' => 1572, 'provinsi_id' => 5, 'nm_kab_kota' => 'Kota Sungai Penuh'],
            ['id' => 1601, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Ogan Komering Ulu'],
            ['id' => 1602, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Ogan Komering Ilir'],


            ['id' => 1603, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Muara Enim'],
            ['id' => 1604, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Lahat'],
            ['id' => 1605, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Musi Rawas'],
            ['id' => 1606, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Musi Banyuasin'],
            ['id' => 1607, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Banyu Asin'],
            ['id' => 1608, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Ogan Komering Ulu Selatan'],
            ['id' => 1609, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Ogan Komering Ulu Timur'],
            ['id' => 1610, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Ogan Ilir'],
            ['id' => 1611, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Empat Lawang'],
            ['id' => 1612, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Penukal Abab Lematang Ilir'],
            ['id' => 1613, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kabupaten Musi Rawas Utara'],
            ['id' => 1671, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kota Palembang'],
            ['id' => 1672, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kota Prabumulih'],
            ['id' => 1673, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kota Pagar Alam'],
            ['id' => 1674, 'provinsi_id' => 6, 'nm_kab_kota' => 'Kota Lubuklinggau'],
            ['id' => 1701, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Bengkulu Selatan'],
            ['id' => 1702, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Rejang Lebong'],
            ['id' => 1703, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Bengkulu Utara'],
            ['id' => 1704, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Kaur'],
            ['id' => 1705, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Seluma'],
            ['id' => 1706, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Mukomuko'],
            ['id' => 1707, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Lebong'],
            ['id' => 1708, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Kepahiang'],
            ['id' => 1709, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kabupaten Bengkulu Tengah'],
            ['id' => 1771, 'provinsi_id' => 7, 'nm_kab_kota' => 'Kota Bengkulu'],
            ['id' => 1801, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Lampung Barat'],
            ['id' => 1802, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Tanggamus'],
            ['id' => 1803, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Lampung Selatan'],
            ['id' => 1804, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Lampung Timur'],
            ['id' => 1805, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Lampung Tengah'],
            ['id' => 1806, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Lampung Utara'],
            ['id' => 1807, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Way Kanan'],
            ['id' => 1808, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Tulangbawang'],
            ['id' => 1809, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Pesawaran'],
            ['id' => 1810, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Pringsewu'],
            ['id' => 1811, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Mesuji'],
            ['id' => 1812, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Tulang Bawang Barat'],
            ['id' => 1813, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kabupaten Pesisir Barat'],
            ['id' => 1871, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kota Bandar Lampung'],
            ['id' => 1872, 'provinsi_id' => 8, 'nm_kab_kota' => 'Kota Metro'],
            ['id' => 1901, 'provinsi_id' => 9, 'nm_kab_kota' => 'Kabupaten Bangka'],
            ['id' => 1902, 'provinsi_id' => 9, 'nm_kab_kota' => 'Kabupaten Belitung'],
            ['id' => 1903, 'provinsi_id' => 9, 'nm_kab_kota' => 'Kabupaten Bangka Barat'],
            ['id' => 1904, 'provinsi_id' => 9, 'nm_kab_kota' => 'Kabupaten Bangka Tengah'],
            ['id' => 1905, 'provinsi_id' => 9, 'nm_kab_kota' => 'Kabupaten Bangka Selatan'],
            ['id' => 1906, 'provinsi_id' => 9, 'nm_kab_kota' => 'Kabupaten Belitung Timur'],
            ['id' => 1971, 'provinsi_id' => 9, 'nm_kab_kota' => 'Kota Pangkal Pinang'],
            ['id' => 2101, 'provinsi_id' => 10, 'nm_kab_kota' => 'Kabupaten Karimun'],
            ['id' => 2102, 'provinsi_id' => 10, 'nm_kab_kota' => 'Kabupaten Bintan'],
            ['id' => 2103, 'provinsi_id' => 10, 'nm_kab_kota' => 'Kabupaten Natuna'],


            ['id' => 2104, 'provinsi_id' => 10, 'nm_kab_kota' => 'Kabupaten Lingga'],
            ['id' => 2105, 'provinsi_id' => 10, 'nm_kab_kota' => 'Kabupaten Kepulauan Anambas'],
            ['id' => 2171, 'provinsi_id' => 10, 'nm_kab_kota' => 'Kota Batam'],
            ['id' => 2172, 'provinsi_id' => 10, 'nm_kab_kota' => 'Kota Tanjung Pinang'],
            ['id' => 3101, 'provinsi_id' => 11, 'nm_kab_kota' => 'Kabupaten Kepulauan Seribu'],
            ['id' => 3171, 'provinsi_id' => 11, 'nm_kab_kota' => 'Kota Jakarta Selatan'],
            ['id' => 3172, 'provinsi_id' => 11, 'nm_kab_kota' => 'Kota Jakarta Timur'],
            ['id' => 3173, 'provinsi_id' => 11, 'nm_kab_kota' => 'Kota Jakarta Pusat'],
            ['id' => 3174, 'provinsi_id' => 11, 'nm_kab_kota' => 'Kota Jakarta Barat'],
            ['id' => 3175, 'provinsi_id' => 11, 'nm_kab_kota' => 'Kota Jakarta Utara'],
            ['id' => 3201, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Bogor'],
            ['id' => 3202, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Sukabumi'],
            ['id' => 3203, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Cianjur'],
            ['id' => 3204, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Bandung'],
            ['id' => 3205, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Garut'],
            ['id' => 3206, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Tasikmalaya'],
            ['id' => 3207, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Ciamis'],
            ['id' => 3208, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Kuningan'],
            ['id' => 3209, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Cirebon'],
            ['id' => 3210, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Majalengka'],
            ['id' => 3211, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Sumedang'],
            ['id' => 3212, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Indramayu'],
            ['id' => 3213, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Subang'],
            ['id' => 3214, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Purwakarta'],
            ['id' => 3215, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Karawang'],
            ['id' => 3216, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Bekasi'],
            ['id' => 3217, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Bandung Barat'],
            ['id' => 3218, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kabupaten Pangandaran'],
            ['id' => 3271, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Bogor'],
            ['id' => 3272, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Sukabumi'],
            ['id' => 3273, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Bandung'],
            ['id' => 3274, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Cirebon'],
            ['id' => 3275, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Bekasi'],
            ['id' => 3276, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Depok'],
            ['id' => 3277, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Cimahi'],
            ['id' => 3278, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Tasikmalaya'],
            ['id' => 3279, 'provinsi_id' => 12, 'nm_kab_kota' => 'Kota Banjar'],
            ['id' => 3301, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Cilacap'],
            ['id' => 3302, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Banyumas'],
            ['id' => 3303, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Purbalingga'],
            ['id' => 3304, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Banjarnegara'],
            ['id' => 3305, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Kebumen'],
            ['id' => 3306, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Purworejo'],
            ['id' => 3307, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Wonosobo'],
            ['id' => 3308, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Magelang'],
            ['id' => 3309, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Boyolali'],
            ['id' => 3310, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Klaten'],
            ['id' => 3311, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Sukoharjo'],
            ['id' => 3312, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Wonogiri'],
            ['id' => 3313, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Karanganyar'],


            ['id' => 3314, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Sragen'],
            ['id' => 3315, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Grobogan'],
            ['id' => 3316, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Blora'],
            ['id' => 3317, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Rembang'],
            ['id' => 3318, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Pati'],
            ['id' => 3319, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Kudus'],
            ['id' => 3320, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Jepara'],
            ['id' => 3321, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Demak'],
            ['id' => 3322, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Semarang'],
            ['id' => 3323, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Temanggung'],
            ['id' => 3324, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Kendal'],
            ['id' => 3325, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Batang'],
            ['id' => 3326, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Pekalongan'],
            ['id' => 3327, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Pemalang'],
            ['id' => 3328, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Tegal'],
            ['id' => 3329, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kabupaten Brebes'],
            ['id' => 3371, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kota Magelang'],
            ['id' => 3372, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kota Surakarta'],
            ['id' => 3373, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kota Salatiga'],
            ['id' => 3374, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kota Semarang'],
            ['id' => 3375, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kota Pekalongan'],
            ['id' => 3376, 'provinsi_id' => 13, 'nm_kab_kota' => 'Kota Tegal'],
            ['id' => 3401, 'provinsi_id' => 14, 'nm_kab_kota' => 'Kabupaten Kulon Progo'],
            ['id' => 3402, 'provinsi_id' => 14, 'nm_kab_kota' => 'Kabupaten Bantul'],
            ['id' => 3403, 'provinsi_id' => 14, 'nm_kab_kota' => 'Kabupaten Gunung Kidul'],
            ['id' => 3404, 'provinsi_id' => 14, 'nm_kab_kota' => 'Kabupaten Sleman'],
            ['id' => 3471, 'provinsi_id' => 14, 'nm_kab_kota' => 'Kota Yogyakarta'],
            ['id' => 3501, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Pacitan'],
            ['id' => 3502, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Ponorogo'],
            ['id' => 3503, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Trenggalek'],
            ['id' => 3504, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Tulungagung'],
            ['id' => 3505, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Blitar'],
            ['id' => 3506, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Kediri'],
            ['id' => 3507, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Malang'],
            ['id' => 3508, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Lumajang'],
            ['id' => 3509, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Jember'],
            ['id' => 3510, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Banyuwangi'],
            ['id' => 3511, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Bondowoso'],
            ['id' => 3512, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Situbondo'],
            ['id' => 3513, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Probolinggo'],
            ['id' => 3514, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Pasuruan'],
            ['id' => 3515, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Sidoarjo'],
            ['id' => 3516, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Mojokerto'],
            ['id' => 3517, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Jombang'],
            ['id' => 3518, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Nganjuk'],
            ['id' => 3519, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Madiun'],
            ['id' => 3520, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Magetan'],
            ['id' => 3521, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Ngawi'],
            ['id' => 3522, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Bojonegoro'],
            ['id' => 3523, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Tuban'],


            ['id' => 3524, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Lamongan'],
            ['id' => 3525, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Gresik'],
            ['id' => 3526, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Bangkalan'],
            ['id' => 3527, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Sampang'],
            ['id' => 3528, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Pamekasan'],
            ['id' => 3529, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kabupaten Sumenep'],
            ['id' => 3571, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Kediri'],
            ['id' => 3572, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Blitar'],
            ['id' => 3573, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Malang'],
            ['id' => 3574, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Probolinggo'],
            ['id' => 3575, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Pasuruan'],
            ['id' => 3576, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Mojokerto'],
            ['id' => 3577, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Madiun'],
            ['id' => 3578, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Surabaya'],
            ['id' => 3579, 'provinsi_id' => 15, 'nm_kab_kota' => 'Kota Batu'],
            ['id' => 3601, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kabupaten Pandeglang'],
            ['id' => 3602, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kabupaten Lebak'],
            ['id' => 3603, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kabupaten Tangerang'],
            ['id' => 3604, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kabupaten Serang'],
            ['id' => 3671, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kota Tangerang'],
            ['id' => 3672, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kota Cilegon'],
            ['id' => 3673, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kota Serang'],
            ['id' => 3674, 'provinsi_id' => 16, 'nm_kab_kota' => 'Kota Tangerang Selatan'],
            ['id' => 5101, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Jembrana'],
            ['id' => 5102, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Tabanan'],
            ['id' => 5103, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Badung'],
            ['id' => 5104, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Gianyar'],
            ['id' => 5105, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Klungkung'],
            ['id' => 5106, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Bangli'],
            ['id' => 5107, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Karang Asem'],
            ['id' => 5108, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kabupaten Buleleng'],
            ['id' => 5171, 'provinsi_id' => 17, 'nm_kab_kota' => 'Kota Denpasar'],
            ['id' => 5201, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Lombok Barat'],
            ['id' => 5202, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Lombok Tengah'],
            ['id' => 5203, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Lombok Timur'],
            ['id' => 5204, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Sumbawa'],
            ['id' => 5205, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Dompu'],
            ['id' => 5206, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Bima'],
            ['id' => 5207, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Sumbawa Barat'],
            ['id' => 5208, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kabupaten Lombok Utara'],
            ['id' => 5271, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kota Mataram'],
            ['id' => 5272, 'provinsi_id' => 18, 'nm_kab_kota' => 'Kota Bima'],
            ['id' => 5301, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Sumba Barat'],
            ['id' => 5302, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Sumba Timur'],
            ['id' => 5303, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Kupang'],
            ['id' => 5304, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Timor Tengah Selatan'],
            ['id' => 5305, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Timor Tengah Utara'],
            ['id' => 5306, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Belu'],
            ['id' => 5307, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Alor'],
            ['id' => 5308, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Lembata'],


            ['id' => 5309, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Flores Timur'],
            ['id' => 5310, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Sikka'],
            ['id' => 5311, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Ende'],
            ['id' => 5312, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Ngada'],
            ['id' => 5313, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Manggarai'],
            ['id' => 5314, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Rote Ndao'],
            ['id' => 5315, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Manggarai Barat'],
            ['id' => 5316, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Sumba Tengah'],
            ['id' => 5317, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Sumba Barat Daya'],
            ['id' => 5318, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Nagekeo'],
            ['id' => 5319, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Manggarai Timur'],
            ['id' => 5320, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Sabu Raijua'],
            ['id' => 5321, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kabupaten Malaka'],
            ['id' => 5371, 'provinsi_id' => 19, 'nm_kab_kota' => 'Kota Kupang'],
            ['id' => 6101, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Sambas'],
            ['id' => 6102, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Bengkayang'],
            ['id' => 6103, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Landak'],
            ['id' => 6104, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Mempawah'],
            ['id' => 6105, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Sanggau'],
            ['id' => 6106, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Ketapang'],
            ['id' => 6107, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Sintang'],
            ['id' => 6108, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Kapuas Hulu'],
            ['id' => 6109, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Sekadau'],
            ['id' => 6110, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Melawi'],
            ['id' => 6111, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Kayong Utara'],
            ['id' => 6112, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kabupaten Kubu Raya'],
            ['id' => 6171, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kota Pontianak'],
            ['id' => 6172, 'provinsi_id' => 20, 'nm_kab_kota' => 'Kota Singkawang'],
            ['id' => 6201, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Kotawaringin Barat'],
            ['id' => 6202, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Kotawaringin Timur'],
            ['id' => 6203, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Kapuas'],
            ['id' => 6204, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Barito Selatan'],
            ['id' => 6205, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Barito Utara'],
            ['id' => 6206, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Sukamara'],
            ['id' => 6207, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Lamandau'],
            ['id' => 6208, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Seruyan'],
            ['id' => 6209, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Katingan'],
            ['id' => 6210, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Pulang Pisau'],
            ['id' => 6211, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Gunung Mas'],
            ['id' => 6212, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Barito Timur'],
            ['id' => 6213, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kabupaten Murung Raya'],
            ['id' => 6271, 'provinsi_id' => 21, 'nm_kab_kota' => 'Kota Palangka Raya'],
            ['id' => 6301, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Tanah Laut'],
            ['id' => 6302, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Kota Baru'],
            ['id' => 6303, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Banjar'],
            ['id' => 6304, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Barito Kuala'],
            ['id' => 6305, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Tapin'],
            ['id' => 6306, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Hulu Sungai Selatan'],
            ['id' => 6307, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Hulu Sungai Tengah'],
            ['id' => 6308, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Hulu Sungai Utara'],


            ['id' => 6309, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Tabalong'],
            ['id' => 6310, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Tanah Bumbu'],
            ['id' => 6311, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kabupaten Balangan'],
            ['id' => 6371, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kota Banjarmasin'],
            ['id' => 6372, 'provinsi_id' => 22, 'nm_kab_kota' => 'Kota Banjar Baru'],
            ['id' => 6401, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kabupaten Paser'],
            ['id' => 6402, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kabupaten Kutai Barat'],
            ['id' => 6403, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kabupaten Kutai Kartanegara'],
            ['id' => 6404, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kabupaten Kutai Timur'],
            ['id' => 6405, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kabupaten Berau'],
            ['id' => 6409, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kabupaten Penajam Paser Utara'],
            ['id' => 6411, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kabupaten Mahakam Hulu'],
            ['id' => 6471, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kota Balikpapan'],
            ['id' => 6472, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kota Samarinda'],
            ['id' => 6474, 'provinsi_id' => 23, 'nm_kab_kota' => 'Kota Bontang'],
            ['id' => 6501, 'provinsi_id' => 24, 'nm_kab_kota' => 'Kabupaten Malinau'],
            ['id' => 6502, 'provinsi_id' => 24, 'nm_kab_kota' => 'Kabupaten Bulungan'],
            ['id' => 6503, 'provinsi_id' => 24, 'nm_kab_kota' => 'Kabupaten Tana Tidung'],
            ['id' => 6504, 'provinsi_id' => 24, 'nm_kab_kota' => 'Kabupaten Nunukan'],
            ['id' => 6571, 'provinsi_id' => 24, 'nm_kab_kota' => 'Kota Tarakan'],
            ['id' => 7101, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Bolaang Mongondow'],
            ['id' => 7102, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Minahasa'],
            ['id' => 7103, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Kepulauan Sangihe'],
            ['id' => 7104, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Kepulauan Talaud'],
            ['id' => 7105, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Minahasa Selatan'],
            ['id' => 7106, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Minahasa Utara'],
            ['id' => 7107, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Bolaang Mongondow Utara'],
            ['id' => 7108, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Siau Tagulandang Biaro'],
            ['id' => 7109, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Minahasa Tenggara'],
            ['id' => 7110, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Bolaang Mongondow Selatan'],
            ['id' => 7111, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kabupaten Bolaang Mongondow Timur'],
            ['id' => 7171, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kota Manado'],
            ['id' => 7172, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kota Bitung'],
            ['id' => 7173, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kota Tomohon'],
            ['id' => 7174, 'provinsi_id' => 25, 'nm_kab_kota' => 'Kota Kotamobagu'],
            ['id' => 7201, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Banggai Kepulauan'],
            ['id' => 7202, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Banggai'],
            ['id' => 7203, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Morowali'],
            ['id' => 7204, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Poso'],
            ['id' => 7205, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Donggala'],
            ['id' => 7206, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Toli-Toli'],
            ['id' => 7207, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Buol'],
            ['id' => 7208, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Parigi Moutong'],
            ['id' => 7209, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Tojo Una-Una'],
            ['id' => 7210, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Sigi'],
            ['id' => 7211, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Banggai Laut'],
            ['id' => 7212, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kabupaten Morowali Utara'],
            ['id' => 7271, 'provinsi_id' => 26, 'nm_kab_kota' => 'Kota Palu'],
            ['id' => 7301, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Kepulauan Selayar'],
            ['id' => 7302, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Bulukumba'],


            ['id' => 7303, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Bantaeng'],
            ['id' => 7304, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Jeneponto'],
            ['id' => 7305, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Takalar'],
            ['id' => 7306, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Gowa'],
            ['id' => 7307, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Sinjai'],
            ['id' => 7308, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Maros'],
            ['id' => 7309, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Pangkajene dan Kepulauan'],
            ['id' => 7310, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Barru'],
            ['id' => 7311, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Bone'],
            ['id' => 7312, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Soppeng'],
            ['id' => 7313, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Wajo'],
            ['id' => 7314, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Sidenreng Rappang'],
            ['id' => 7315, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Pinrang'],
            ['id' => 7316, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Enrekang'],
            ['id' => 7317, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Luwu'],
            ['id' => 7318, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Tana Toraja'],
            ['id' => 7322, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Luwu Utara'],
            ['id' => 7325, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Luwu Timur'],
            ['id' => 7326, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kabupaten Toraja Utara'],
            ['id' => 7371, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kota Makassar'],
            ['id' => 7372, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kota Parepare'],
            ['id' => 7373, 'provinsi_id' => 27, 'nm_kab_kota' => 'Kota Palopo'],
            ['id' => 7401, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Buton'],
            ['id' => 7402, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Muna'],
            ['id' => 7403, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Konawe'],
            ['id' => 7404, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Kolaka'],
            ['id' => 7405, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Konawe Selatan'],
            ['id' => 7406, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Bombana'],
            ['id' => 7407, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Wakatobi'],
            ['id' => 7408, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Kolaka Utara'],
            ['id' => 7409, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Buton Utara'],
            ['id' => 7410, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Konawe Utara'],
            ['id' => 7411, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Kolaka Timur'],
            ['id' => 7412, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Konawe Kepulauan'],
            ['id' => 7413, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Muna Barat'],
            ['id' => 7414, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Buton Tengah'],
            ['id' => 7415, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kabupaten Buton Selatan'],
            ['id' => 7471, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kota Kendari'],
            ['id' => 7472, 'provinsi_id' => 28, 'nm_kab_kota' => 'Kota Baubau'],
            ['id' => 7501, 'provinsi_id' => 29, 'nm_kab_kota' => 'Kabupaten Boalemo'],
            ['id' => 7502, 'provinsi_id' => 29, 'nm_kab_kota' => 'Kabupaten Gorontalo'],
            ['id' => 7503, 'provinsi_id' => 29, 'nm_kab_kota' => 'Kabupaten Pohuwato'],
            ['id' => 7504, 'provinsi_id' => 29, 'nm_kab_kota' => 'Kabupaten Bone Bolango'],
            ['id' => 7505, 'provinsi_id' => 29, 'nm_kab_kota' => 'Kabupaten Gorontalo Utara'],
            ['id' => 7571, 'provinsi_id' => 29, 'nm_kab_kota' => 'Kota Gorontalo'],
            ['id' => 7601, 'provinsi_id' => 30, 'nm_kab_kota' => 'Kabupaten Majene'],
            ['id' => 7602, 'provinsi_id' => 30, 'nm_kab_kota' => 'Kabupaten Polewali Mandar'],
            ['id' => 7603, 'provinsi_id' => 30, 'nm_kab_kota' => 'Kabupaten Mamasa'],
            ['id' => 7604, 'provinsi_id' => 30, 'nm_kab_kota' => 'Kabupaten Mamuju'],
            ['id' => 7605, 'provinsi_id' => 30, 'nm_kab_kota' => 'Kabupaten Mamuju Utara'],


            ['id' => 7606, 'provinsi_id' => 30, 'nm_kab_kota' => 'Kabupaten Mamuju Tengah'],
            ['id' => 8101, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Maluku Tenggara Barat'],
            ['id' => 8102, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Maluku Tenggara'],
            ['id' => 8103, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Maluku Tengah'],
            ['id' => 8104, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Buru'],
            ['id' => 8105, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Kepulauan Aru'],
            ['id' => 8106, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Seram Bagian Barat'],
            ['id' => 8107, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Seram Bagian Timur'],
            ['id' => 8108, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Maluku Barat Daya'],
            ['id' => 8109, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kabupaten Buru Selatan'],
            ['id' => 8171, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kota Ambon'],
            ['id' => 8172, 'provinsi_id' => 31, 'nm_kab_kota' => 'Kota Tual'],
            ['id' => 8201, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Halmahera Barat'],
            ['id' => 8202, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Halmahera Tengah'],
            ['id' => 8203, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Kepulauan Sula'],
            ['id' => 8204, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Halmahera Selatan'],
            ['id' => 8205, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Halmahera Utara'],
            ['id' => 8206, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Halmahera Timur'],
            ['id' => 8207, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Pulau Morotai'],
            ['id' => 8208, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kabupaten Pulau Taliabu'],
            ['id' => 8271, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kota Ternate'],
            ['id' => 8272, 'provinsi_id' => 32, 'nm_kab_kota' => 'Kota Tidore Kepulauan'],
            ['id' => 9101, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Fakfak'],
            ['id' => 9102, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Kaimana'],
            ['id' => 9103, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Teluk Wondama'],
            ['id' => 9104, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Teluk Bintuni'],
            ['id' => 9105, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Manokwari'],
            ['id' => 9106, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Sorong Selatan'],
            ['id' => 9107, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Sorong'],
            ['id' => 9108, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Raja Ampat'],
            ['id' => 9109, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Tambrauw'],
            ['id' => 9110, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Maybrat'],
            ['id' => 9111, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Manokwari Selatan'],
            ['id' => 9112, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kabupaten Pegunungan Arfak'],
            ['id' => 9171, 'provinsi_id' => 33, 'nm_kab_kota' => 'Kota Sorong'],
            ['id' => 9401, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Merauke'],
            ['id' => 9402, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Jayawijaya'],
            ['id' => 9403, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Jayapura'],
            ['id' => 9404, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Nabire'],
            ['id' => 9408, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Kepulauan Yapen'],
            ['id' => 9409, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Biak Numfor'],
            ['id' => 9410, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Paniai'],
            ['id' => 9411, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Puncak Jaya'],
            ['id' => 9412, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Mimika'],
            ['id' => 9413, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Boven Digoel'],
            ['id' => 9414, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Mappi'],
            ['id' => 9415, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Asmat'],
            ['id' => 9416, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Yahukimo'],
            ['id' => 9417, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Pegunungan Bintang'],
            ['id' => 9418, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Tolikara'],


            ['id' => 9419, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Sarmi'],
            ['id' => 9420, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Keerom'],
            ['id' => 9426, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Waropen'],
            ['id' => 9427, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Supiori'],
            ['id' => 9428, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Mamberamo Raya'],
            ['id' => 9429, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Nduga'],
            ['id' => 9430, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Lanny Jaya'],
            ['id' => 9431, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Mamberamo Tengah'],
            ['id' => 9432, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Yalimo'],
            ['id' => 9433, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Puncak'],
            ['id' => 9434, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Dogiyai'],
            ['id' => 9435, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Intan Jaya'],
            ['id' => 9436, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kabupaten Deiyai'],
            ['id' => 9471, 'provinsi_id' => 34, 'nm_kab_kota' => 'Kota Jayapura']

        ];

        foreach ($data as $value) {
            Kota::create($value);
        }
    }
}
